const COSMETIC_CATALOG = [
  // Card backs
  {
    id: 'card-back-black',
    type: 'cardBack',
    name: 'Midnight Back',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/basic/card-back-black.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-black.png',
  },
  {
    id: 'card-back-blue',
    type: 'cardBack',
    name: 'Ocean Back',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/basic/card-back-blue.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-blue.png',
  },
  {
    id: 'card-back-green',
    type: 'cardBack',
    name: 'Emerald Back',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/basic/card-back-green.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-green.png',
  },
  {
    id: 'card-back-orange',
    type: 'cardBack',
    name: 'Sunset Back',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/basic/card-back-orange.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-orange.png',
  },
  {
    id: 'card-back-purple',
    type: 'cardBack',
    name: 'Arcane Back',
    price_cents: 0,
    rarity: 'uncommon',
    preview: '/assets/cosmetics/cards/basic/card-back-purple.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-purple.png',
  },
  {
    id: 'card-back-purple-svg',
    type: 'cardBack',
    name: 'Vector Neon Back',
    price_cents: 0,
    rarity: 'uncommon',
    preview: '/assets/cosmetics/cards/basic/card-back-purple.svg',
    image_url: '/assets/cosmetics/cards/basic/card-back-purple.svg',
  },
  {
    id: 'card-back-red',
    type: 'cardBack',
    name: 'Inferno Back',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/basic/card-back-red.png',
    image_url: '/assets/cosmetics/cards/basic/card-back-red.png',
  },

  // Card face placeholder
  {
    id: 'card-face-ace-of-spades',
    type: 'cardFace',
    name: 'Classic Ace of Spades',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/cards/faces/ace_of_spades.svg',
    image_url: '/assets/cosmetics/cards/faces/ace_of_spades.svg',
  },

  // Avatar rings
  {
    id: 'avatar-basic-1',
    type: 'avatarRing',
    name: 'Basic Ring 1',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/avatar/basic-extra1.png',
    image_url: '/assets/cosmetics/avatar/basic-extra1.png',
  },
  {
    id: 'avatar-basic-2',
    type: 'avatarRing',
    name: 'Basic Ring 2',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/avatar/basic-extra2.png',
    image_url: '/assets/cosmetics/avatar/basic-extra2.png',
  },
  {
    id: 'avatar-drop-pink-neon',
    type: 'avatarRing',
    name: 'Drop Pink Neon',
    price_cents: 0,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/drop-pink-neon.png',
    image_url: '/assets/cosmetics/avatar/drop-pink-neon.png',
    unlock_type: 'twitch_drop',
  },
  {
    id: 'avatar-fire-ring',
    type: 'avatarRing',
    name: 'Fire Ring',
    price_cents: 150,
    rarity: 'uncommon',
    preview: '/assets/cosmetics/avatar/fire_ring.svg',
    image_url: '/assets/cosmetics/avatar/fire_ring.svg',
  },
  {
    id: 'avatar-streamer-cosmic',
    type: 'avatarRing',
    name: 'Streamer Cosmic',
    price_cents: 0,
    rarity: 'epic',
    preview: '/assets/cosmetics/avatar/streamer-cosmic.png',
    image_url: '/assets/cosmetics/avatar/streamer-cosmic.png',
    unlock_type: 'streamer_goal',
    unlock_value: 50,
  },
  {
    id: 'avatar-streamer-glitch',
    type: 'avatarRing',
    name: 'Streamer Glitch',
    price_cents: 0,
    rarity: 'epic',
    preview: '/assets/cosmetics/avatar/streamer-glitch.png',
    image_url: '/assets/cosmetics/avatar/streamer-glitch.png',
    unlock_type: 'twitch_drop',
  },
  {
    id: 'avatar-streamer-gold',
    type: 'avatarRing',
    name: 'Streamer Gold',
    price_cents: 0,
    rarity: 'legendary',
    preview: '/assets/cosmetics/avatar/streamer-gold.png',
    image_url: '/assets/cosmetics/avatar/streamer-gold.png',
    unlock_type: 'streamer_goal',
    unlock_value: 75,
  },
  {
    id: 'avatar-streamer-neon',
    type: 'avatarRing',
    name: 'Streamer Neon',
    price_cents: 300,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/streamer-neon.png',
    image_url: '/assets/cosmetics/avatar/streamer-neon.png',
  },
  {
    id: 'avatar-subscriber-cosmic',
    type: 'avatarRing',
    name: 'Subscriber Cosmic',
    price_cents: 0,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/subscriber-cosmic.png',
    image_url: '/assets/cosmetics/avatar/subscriber-cosmic.png',
    unlock_type: 'subscriber',
  },
  {
    id: 'avatar-subscriber-frost',
    type: 'avatarRing',
    name: 'Subscriber Frost',
    price_cents: 0,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/subscriber-frost.png',
    image_url: '/assets/cosmetics/avatar/subscriber-frost.png',
    unlock_type: 'subscriber',
  },
  {
    id: 'avatar-subscriber-purple-neon',
    type: 'avatarRing',
    name: 'Subscriber Purple Neon',
    price_cents: 0,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/subscriber-purple-neon.png',
    image_url: '/assets/cosmetics/avatar/subscriber-purple-neon.png',
    unlock_type: 'subscriber',
  },
  {
    id: 'avatar-subscriber-sparkle',
    type: 'avatarRing',
    name: 'Subscriber Sparkle',
    price_cents: 0,
    rarity: 'rare',
    preview: '/assets/cosmetics/avatar/subscriber-sparkle.png',
    image_url: '/assets/cosmetics/avatar/subscriber-sparkle.png',
    unlock_type: 'subscriber',
  },

  // Table skins
  {
    id: 'table-neon-green',
    type: 'table',
    name: 'Neon Green Felt',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/table/neon_green.svg',
    image_url: '/assets/cosmetics/table/neon_green.svg',
  },
  {
    id: 'table-basic-neon-twitch',
    type: 'table',
    name: 'Basic Neon Twitch',
    price_cents: 0,
    rarity: 'uncommon',
    preview: '/assets/cosmetics/table/basic/table_streamer_neon_twitch.png',
    image_url: '/assets/cosmetics/table/basic/table_streamer_neon_twitch.png',
  },
  {
    id: 'table-drop-glitch-twitch',
    type: 'table',
    name: 'Glitch Twitch Table',
    price_cents: 0,
    rarity: 'epic',
    preview: '/assets/cosmetics/table/drops/table_streamer_glitch_twitch.png',
    image_url: '/assets/cosmetics/table/drops/table_streamer_glitch_twitch.png',
    unlock_type: 'twitch_drop',
  },
  {
    id: 'table-streamer-cosmic-moon',
    type: 'table',
    name: 'Streamer Cosmic Moon',
    price_cents: 0,
    rarity: 'epic',
    preview: '/assets/cosmetics/table/streamer/table_streamer_cosmic_moon.png',
    image_url: '/assets/cosmetics/table/streamer/table_streamer_cosmic_moon.png',
    unlock_type: 'streamer_goal',
  },
  {
    id: 'table-streamer-gold-crown',
    type: 'table',
    name: 'Streamer Gold Crown',
    price_cents: 0,
    rarity: 'legendary',
    preview: '/assets/cosmetics/table/streamer/table_streamer_gold_crown.png',
    image_url: '/assets/cosmetics/table/streamer/table_streamer_gold_crown.png',
    unlock_type: 'streamer_goal',
  },
  {
    id: 'table-streamer-gold-star',
    type: 'table',
    name: 'Streamer Gold Star',
    price_cents: 0,
    rarity: 'legendary',
    preview: '/assets/cosmetics/table/streamer/table_streamer_gold_star.png',
    image_url: '/assets/cosmetics/table/streamer/table_streamer_gold_star.png',
    unlock_type: 'streamer_goal',
  },
  {
    id: 'table-streamer-neon-twitch',
    type: 'table',
    name: 'Streamer Neon Twitch',
    price_cents: 0,
    rarity: 'epic',
    preview: '/assets/cosmetics/table/streamer/table_streamer_neon_twitch.png',
    image_url: '/assets/cosmetics/table/streamer/table_streamer_neon_twitch.png',
    unlock_type: 'streamer_goal',
  },

  // Frames / nameplates
  {
    id: 'frame-neon-nameplate',
    type: 'nameplate',
    name: 'Neon Nameplate',
    price_cents: 100,
    rarity: 'rare',
    preview: '/assets/cosmetics/frame/neon_nameplate.svg',
    image_url: '/assets/cosmetics/frame/neon_nameplate.svg',
  },

  // Chips
  {
    id: 'chips-classic-100',
    type: 'chips',
    name: 'Classic 100 Stack',
    price_cents: 0,
    rarity: 'common',
    preview: '/assets/cosmetics/chips/chip-100-top.svg',
    image_url: '/assets/cosmetics/chips/chip-100-top.svg',
  },
];

module.exports = { COSMETIC_CATALOG };
